### ISSUE TITLE
Stop Importing `mpi4py` by Default

### ISSUE THREAD

**Issue by akleb** [mdolab/baseclasses#68] opened 2021-09-24 19:16 UTC
# Description of feature

Similar to the reasoning presented in mdolab/pygeo#85. It would be useful to import `BaseSolver` without importing `mpi4py`. The problem occurs in the `__init__.py` where `BaseRegTest` is imported. The  [no-mpi](https://github.com/mdolab/baseclasses/tree/no-mpi) branch removes the problematic line

# Potential solution

This is a backward compatibility breaking change, but a potential fix is to remove the `import BaseRegTest` from the `__init__.py`

**Comment by marcomangano** [comment] 2021-10-03 15:53
Shall we close this for now? @nwu63 @anilyil @akleb

**Comment by anilyil** [comment] 2021-10-04 00:27
Up to @akleb. I suggest we close this as I think the issue is more general and is related to xflow and using it in parallel with python.

**Closed** 2021-10-04 13:18 UTC
